### PR TITLE
make forward reference in block ineligible

### PR DESCRIPTION
**Pull request by backuitist**
Do not allow the following:
```
def build: B = {
  val b = wire[B]
  val forwardA = A() // forward reference is ineligible
}
```

### CODE REVIEW

**Comment by adamw** [comment]
Won't that break:
```
class A
class B(a: A)
lazy val b = wire[B]
lazy val a = wire[A]
```
?

**Comment by backuitist** [comment]
This check only applies in block. The devil is in the details...
This works:
```scala
object Test {
    lazy val b = wire[B]
    val forwardA = A()
}
```
But this doesn't (`forward reference extends over definition of value forwardA`):
```scala
object Test {
    def build: B = {
        lazy val b = wire[B]
        val forwardA = A()
        b
    }
}
```
And you're right, this could work but is forbidden by this commit:
```scala
object Test {
    def build: B = {
        lazy val b = wire[B]
        lazy val forwardA = A()
        b
    }
}
```
For the record, this breaks:
```scala
object Test {
    def build: B = {
        val b = wire[B]
        lazy val forwardA = A()
        b
    }
}
```

So basically you'd have to make sure that your wire call is not affected to a non-lazy val AND that the subsequent declarations are lazy.
We could lodge a bug/feature but IMO in a block it's a bit twisted to wire forward references (even lazy ones).

**Comment by backuitist** [comment]
I've described that rational in the commit message & a todo test-case.

**Comment by adamw** [comment]
Well using `lazy val`s to let the compiler figure out the wiring order is kind of a "core feature", so I would be reluctant to change this in one place (a block).

Also, in your test you wire with an inherited `A` instead of the one declared later. Shouldn't this result in an error? I think chances might be quite high that the presence of two `A`s (although one declared later) is a programming error, not intentional. For that I think the `wire[B](specificA)` syntax would be much better.

**Comment by backuitist** [comment]
I all depend on what kind of error message you'd like in this situation:
```scala
object Test {
    def build: B = {
        lazy val b = wire[B]
        val forwardA = A()
        b
    }
}
```
Currently you'll get `forward reference extends over definition of value forwardA`, with this commit you'll have `cannot find a value of type A`. Generally speaking I don't like macros that produce erroneous code that cannot compile.

I've made forward references in blocks ineligible so in the test the only eligible value found is in the parent. I'd be tricky though, given the current mechanic, to fail with an ambiguous error message - and IMO not desirable (it would be a weird ambiguity: between an unreachable value and an eligible one).

Now, I don't have super strong feeling regarding this PR so that's up to you :)

**Comment by backuitist** [comment]
Just thinking of this right now, maybe you'd like a better error message from the macwire: `cannot find a value of type A. Note that [forwardA] would match but is unreachable as it is declared after the wire call`?

**Comment by adamw** [comment]
Sure, that would be way better. Good error messages are always a nice thing to have :) I wouldn't let that example with the parent-A and forward-A compile, though.

**Comment by backuitist** [comment]
> I wouldn't let that example with the parent-A and forward-A compile, though.

What would be the error message then? `cannot find a value of type a` even though there is one?

**Comment by adamw** [comment]
Well I would say it's an ambiguous-A error, as there are two values of type `A`, even though using one would cause another compilation error, but there's definitely a strong possibility that it's a bug

Another option is to emit a warning that a forward-A reference is not taken into account, but instead another value is used?

**Comment by backuitist** [comment]
I like the warning idea.

**Comment by backuitist** [comment]
There you go, with the warning ;)

**Comment by adamw** [comment]
Will this also emit a warning for a forward reference to a `lazy val` in e.g. a `trait`? (not in a block)

**Comment by backuitist** [comment]
If the wire call isn't in a block there won't be any value in the `LocalForward` scope, therefore no warning will be emitted. I'm adding a test to demonstrate that.

**Comment by backuitist** [comment]
Note that successful test-cases are now required to be free of warnings. BTW I've had to change a test for that matter: statements such as `2+2` would trigger a compiler warning (`a pure expression does nothing in statement position...`).

**Comment by adamw** [comment]
Right, thanks :)

**Pull request merged**
