### PR TITLE
Iron out module

### PR DESCRIPTION
**Pull request by backuitist**
This should be the last changes over the module feature - at least for 2.0.0.
Note that I've worked off the previous PR as it seems to me that you approved it.
Regarding 2.0.0, I've had a problem with the companion object feature #64 so I'd suggest to leave it for later and go ahead with the release.

### CODE REVIEW

**Comment by adamw** [comment]
Doesn't this contain chanages from PR #69 as well?

**Comment by backuitist** [comment]
Yep, that's what I said in the PR description ;)

**Comment by backuitist** [comment]
I've rebased for you :)

**Comment by adamw** [comment]
Thanks :)

**Pull request merged**
