### PR TITLE
Issue 126 - Fixed Bug - Resolve type parameters when inspecting parent traits

### PR DESCRIPTION
**Pull request by jimmydivvy**
This resolves https://github.com/adamw/macwire/issues/126

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! Could you maybe add a test case for this? Adding a file to https://github.com/adamw/macwire/tree/master/tests/src/test/resources/test-cases should do the trick :)

**Comment by jimmydivvy** [comment]
Test cases added.

**Comment by jimmydivvy** [comment]
Thanks for merging that. 

If you're comfortable releasing this as 2.3.2, would you like me to raise a PR to backport this to 2.3.x as well for a quick point release?

**Comment by adamw** [comment]
I just released 2.3.2, should be in central soon :)

**Pull request merged**
