### PR TITLE
support self-types

### LINKED ISSUE #31: Compile error on expressing the dependencies via self-types
`wire[T]` fails to lookup the instance when using self-types (although it works when extending the other trait). 

For instance the code block:

```scala
class A
class B(a: A)

trait ModuleA {
  lazy val a = wire[A]
}

trait ModuleB {
  self: ModuleA =>
  lazy val b = wire[B]
}
```
gets the following compile error:
```
Cannot find a value of type: [~.A]
[error]   lazy val b = wire[B]
[error]                    ^
```

### PR DESCRIPTION
**Pull request by backuitist**
Fix #31.

### CODE REVIEW

**Comment by adamw** [comment]
Same here - contains too much changes :)

**Comment by backuitist** [comment]
There's the import rename fix because I'm a bit lazy ;)

**Comment by backuitist** [comment]
There you go, thanks for merging the others!

**Comment by adamw** [comment]
Thanks :)

**Pull request merged**
