### PR TITLE
Implement wireResource for scala 2

### PR DESCRIPTION
**Pull request by mbore**

### CODE REVIEW

**Comment by adamw** [comment]
One more naming idea: `wireAuto` in the package `macwire.auto.cats`?

**Comment by adamw** [comment]
Looks good :) There's a lot of tests to add, though. Maybe I'll just add them and then we'll have sth like TDD ;)

One thing that we'll need to decide is how to re-use instances. Right now we are re-using anything that is created by a resource - and this makes sense. When creating an instance of a class, do we want to re-use it? That is, should the following (assuming not only `Resource`s are implemented):

```scala
case class A
case class B(a1: A, a2: A)

val b = wireX[B]
```

generate either (1):

```scala
val b = B(A(), A())
```

or (2):

```scala
val b = {
  val x = A()
  B(x, x)
}
```

Here it doesn't make a difference, but maybe for some cases it does make a difference whether a dependency is a singleton and re-used, or not. 

Probably (1) is the better default, as it follows other DI frameworks where "dependent" scope is the default. And we could achieve singleton by explicitly passing in the instance. So I guess that's solved, or do you have another opinion? :)

**Comment by mbore** [comment]
Actually I'm still not sure if we want to support no parameters constructors. 
It may cause difficult to debug mistakes like "forgot to pass filled config", for example:
```Scala
import cats.effect._
import cats.effect.unsafe.implicits.global

class MutableConfig() {
  var port: Option[Int] = None
  var host: Option[String] = None
}

class Service(cfg: MutableConfig) {
  println(s"[${cfg.host}]:[${cfg.port}]")
}

object Main extends App {

  def loadConfig(): Resource[IO, MutableConfig] = Resource.pure {
    val mc = new MutableConfig()
    mc.host = Some("xyz")
    mc.port = Some(8080)

    mc
  }

  val cfg = loadConfig()

  val service = autowire[Service]()

  service.allocated.unsafeRunSync()._1

}
```
it works and prints `[None]:[None]`. 
I see that it may reduce boilerplate in some cases, but I'm not sure if it's worth to risk.

**Comment by adamw** [comment]
@mbore I've moved the no-arg constructor problem to https://github.com/softwaremill/macwire/issues/184 as well

**Pull request merged**
