### PR TITLE
wiring from import

### PR DESCRIPTION
**Pull request by backuitist**
Take a look at the test cases.

### CODE REVIEW

**Comment by adamw** [comment]
I'm not sure about this one.

First, it would require at least a minor version change, as it's possible that code which was unambiguous before is ambiguous now (because of the imports).

Secondly, this only takes into account `import` statement that are inside the "surrounding block" (method/object/trait). That could be counter-intuitive, as why are values which are imported globally not taken into account?

It would be best to wire with all values that are currently "in scope", but that's unfortunately not possible with the current scala macros impl.

**Comment by backuitist** [comment]
1) Well I'm not against a 1.1.0 release :)
2) It's more counter intuitive to me that a local import isn't taken into account. I have the following use case in mind:

    class Extension(coreModule: CoreModule) {
      import coreModule._

      lazy val stuff = wire[Stuff]
    }

Composition over inheritance.

> It would be best to wire with all values that are currently "in scope", but that's unfortunately not possible with the current scala macros impl.

I would actually rather not wire stuff that are outside the scope.

**Comment by backuitist** [comment]
So this is counter intuitive:
```scala
object Test {
    lazy val theA = wire[A]
    lazy val theB = wire[B]
}
    
object App {
    import Test._
    object A {
        val theC = wire[C]
    }
}
```

How about this:
```scala
object Test {
    lazy val theA = wire[A]
    lazy val theB = wire[B]

    object A {
        val theC = wire[C]
    }
}
```

**Comment by adamw** [comment]
I agree that using only the nearest enclosing object/method/etc. is counter-intuitive, but that's a limitation of macros which unfortunately I can't overcome right now. Maybe the imports could work - I like your example. Let me think about ti, I'll take a look at some more options in a couple of days

Still I think wiring using values which are "in scope" would be the least surprising - this would use values just as you use them in all other places. Maybe in ScalaMeta :)

**Comment by backuitist** [comment]
I've created issue #51 so that other people might say something.

**Comment by adamw** [comment]
After thinking this through I really like your "extension" example. Maybe you could add it to the readme?

**Comment by backuitist** [comment]
Great! The PR already contained the README update.

**Comment by adamw** [comment]
Yeah but I was thinking about adding the "extend a module" example to the readme, above an easy-to-miss statement on where values are searched for :)

**Comment by backuitist** [comment]
Right, I'll write something in another PR.

**Comment by backuitist** [comment]
Ok, what do you think of this: https://github.com/di-in-scala/di-in-scala.github.io-sources/pull/2

**Pull request merged**
